# Site settings
title: Kazamatsuri Podcast
subtitle: Podcast Test
author: Kazamatsuri
email: podcast@kazamatsuri.org
description: > # this means to ignore newlines until "baseurl:"
  Podcast of the Kazamatsuri community. We are a home for fans of Key's works dedicated to covering all the latest Key news and analysing and discussing their stories together.
link: "http://kazamatsuri.org/"

# Audio source settings
audio_baseurl: "http://d2qdztz5tk5zxi.cloudfront.net/podcast/"
audio_types:
  - name: MP3
    ext: mp3
    mime: audio/mpeg

# Contact information
owner_name: Aspirety
owner_email: aspirety@kazamatsuri.org
twitter_username: KazamatsuriOrg

# Paths, don't change these
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://podcast.kazamatsuri.org" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
